baseurl: ""
lang: "fr"
include: ["_pages"]

paginate: 5
paginate_path: "/page-:num/"

permalink: "/:year/:month/:day/:title"
timezone: "Europe/Paris"

excerpt_separator: "<!-- more -->"

collections:
    members:
        permalink: "/membres/:path"

    sets:
        permalink: "/series/:path"

    episodes:
        permalink: "/episodes/:path"

gems:
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-redirect-from"
    - "jekyll-sitemap"





prose:
    media: "media"
    rooturl: ""

    siteurl: "https://rwby-vostfr.github.io/"
    relativeLinks: "https://rwby-vostfr.github.io/prose-relative-links.jsonp"

    metadata:
        _posts:
            -
                name: "layout"
                field: { element: "hidden", value: "blog" }
            -
                name: "title"
                field: { element: "text", label: "Titre" }
            -
                name: "date"
                field: { element: "text", placeholder: "yyyy-mm-dd hh:mm:ss", label: "Date" }
            -
                name: "category"
                field: { element: "hidden", value: "blog" }
            -
                name: "tags"
                field: { element: "multiselect", label: "Tags" }
            -
                name: "published"
                field: { element: "checkbox", value: false, label: "Publié" }

        _pages:
            -
                name: "layout"
                field: { element: "hidden", value: "page" }
            -
                name: "title"
                field: { element: "text", label: "Titre" }
            -
                name: "permalink"
                field: { element: "text", label: "Lien permanent" }
            -
                name: "published"
                field: { element: "checkbox", value: true, label: "Publié" }
