baseurl: ""
lang: "fr"
meta_title: "RWBY VOSTFR"
description: "Site communautaire français autour de la série RWBY de RoosterTeeth"

timezone: "Europe/Paris"

collections:
    pages:
        output: true

    members: ~
    sets: ~

    episodes:
        output: true

gems:
    - "jekyll-redirect-from"
    - "jekyll-sitemap"



prose:
    media: "media"
    rooturl: ""

    siteurl: "https://rwby-vostfr.github.io/"
    relativeLinks: "https://rwby-vostfr.github.io/prose-relative-links.jsonp"

    metadata:
        _pages:
            -
                name: "layout"
                field: { element: "hidden", value: "page" }
            -
                name: "title"
                field: { element: "text", label: "Titre" }
            -
                name: "permalink"
                field: { element: "text", label: "Lien permanent" }
            -
                name: "published"
                field: { element: "checkbox", value: true, label: "Publié" }

        _members:
            -
                name: "id"
                field: { element: "text", label: "id" }
            -
                name: "name"
                field: { element: "text", label: "Nom" }
            -
                name: "published"
                field: { element: "checkbox", value: true, label: "Publié" }

        _sets:
            -
                name: "layout"
                field: { element: "hidden", value: "set" }
            -
                name: "slug"
                field: { element: "text", label: "Slug" }
            -
                name: "name"
                field: { element: "text", label: "Nom" }
            -
                name: "permalink"
                field: { element: "text", label: "Lien permanent" }
            -
                name: "published"
                field: { element: "checkbox", value: true, label: "Publié" }

        _episodes:
            -
                name: "layout"
                field: { element: "hidden", value: "episode" }
            -
                name: "set"
                field: { element: "text", label: "Collection" }
            -
                name: "number"
                field: { element: "number", label: "Numéro" }
            -
                name: "name"
                field: { element: "text", label: "Nom" }
            -
                name: "permalink"
                field: { element: "text", label: "Lien permanent" }
            -
                name: "published"
                field: { element: "checkbox", value: true, label: "Publié" }
