baseurl: ""
lang: "fr"
include: ["_pages"]

paginate: 5
paginate_path: "/page-:num/"

permalink: "/:year/:month/:day/:title"
timezone: "Europe/Paris"

excerpt_separator: "<!-- more -->"

collections:
    members:
        permalink: "/membres/:path"

    sets:
        permalink: "/series/:path"

    episodes:
        permalink: "/episodes/:path"

gems:
    - "jekyll-paginate"
    - "jekyll-feed"
    - "jekyll-redirect-from"
    - "jekyll-sitemap"





prose:
    media: "media"
    rooturl: "."
    ignore:
        - "_data"
        - "_includes"
        - "_layouts"
        - "_config.yml"
        - "_config.yml"
        - "_prose.yml"
        - ".gitignore"
        - "prose-relative-links.jsonp"

    siteurl: "https://rwby-vostfr.github.io/"
    relativeLinks: "https://rwby-vostfr.github.io/prose-relative-links.jsonp"

    metadata:
        _posts:
            -
                name: "layout"
                field: { element: "hidden", value: "blog" }
            -
                name: "title"
                field: { element: "text" }
            -
                name: "date"
                field: { element: "text", value: "CURRENT_DATETIME" }
            -
                name: "category"
                field: { element: "hidden", value: "blog" }
            -
                name: "tags"
                field: { element: "multiselect", alterable: true }
            -
                name: "published"
                field: { element: "checkbox", value: false }

        _pages:
            -
                name: "layout"
                field: { element: "hidden", value: "page" }
            -
                name: "title"
                field: { element: "text" }
            -
                name: "permalink"
                field: { element: "text" }
            -
                name: "published"
                field: { element: "checkbox", value: true }
